version: '2.4'
services:
    postgres_local:
      image: "postgres:13.3-alpine"
      ports:
<<<<<<< HEAD
        - "5532:5432"
      env_file:
        - .env
=======
        - "65432:5432"
>>>>>>> 1f075e83828b996cb797abece7280655abe942e8
      volumes:
        - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: