version: '2.4'

services:

    postgres_local:
      image: "postgres:13.3-alpine"
      ports:
        - "5532:5432"
      env_file:
        - .env
      volumes:
        - ./.pgdata:/var/lib/postgresql/data